const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const P=require('../static/js/physics.js'), read=n=>JSON.parse(fs.readFileSync(path.join(__dirname,'../static/data',n))), cat=P.catalogue(read('nuclear-states.json'),read('ame2020.json'));
const near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`),ion=(s,q=1,w=1)=>cat.resolve(s,{q,w}),p={laps:1000,referenceUs:10,lapUs:8,widthNs:20,broadeningNs:.02,delayUs:0};
test('state bookmarks display records even when ion mass or excitation is unavailable',()=>{
 const limited=[...cat.states.values()].find(s=>s.source_state_index&&(s.excitation.value===null||s.excitation.qualifier));
 assert.ok(limited);assert.equal(cat.lookupState(limited.A+limited.element,limited.source_state_index),limited);
 assert.equal(cat.lookupState('116Sn',0).id,'50-66-0');
 assert.equal(cat.lookupState('116Sn','bad'),null);assert.equal(cat.lookupState('116Sn',999),null);
});
test('known isotope, sixth isomer, molecules, charge and unavailable state',()=>{near(ion('12C').M,12);assert.equal(ion('98Ym6').atoms[0].state.id,'39-59-6');near(ion('12C11').M,132);near(ion('12C16O2').M,ion('12C').M+2*ion('16O').M);assert.equal(ion('133Cs+2').q,2);assert.throws(()=>ion('133Xe[m9]'));assert.throws(()=>ion('133Xe[9]'));assert.throws(()=>ion('12C',7));assert.throws(()=>ion('133Xe',1,-1));});
test('source precision, uncertainty cancellation and unknown uncertainty',()=>{const g=ion('133Xe'),m=ion('133mXe'),d=P.combine([1,m.value],[-1,g.value]);near(d.v*P.C.uKeV,233.221,1e-10);near(d.e*P.C.uKeV,.015,1e-12);const a=P.primitive('separate-flags',1,.1,false,true);assert.equal(P.combine([1,a]).sigmaEst,true);assert.equal(P.combine([1,a]).est,false);assert.equal(P.combine([1,a],[-1,a]).sigmaEst,false);const x=P.primitive('unknown',1,null,true);assert.equal(P.combine([1,x]).e,null);assert.equal(P.combine([1,x],[-1,x]).e,0);assert.equal(P.combine([1,x],[-1,x]).est,false);});
test('exact flight scaling, charges, electronic delay and zero separation',()=>{const a=ion('133Xe'),b=ion('133Xe',2);const m=P.mrtof([a,b],p);near(m.species[1].flight/m.species[0].flight,Math.sqrt(b.ionMassU/(2*a.ionMassU)));const late=P.mrtof([a,b],{...p,delayUs:100});near(late.pairs[0].dt,m.pairs[0].dt,1e-8);near(late.species[0].survival,m.species[0].survival);near(P.mrtof([a,a],p).pairs[0].dt,0);near(m.species.reduce((s,x)=>s+x.w,0),1);assert.throws(()=>P.mrtof([a],{...p,laps:.5}));});
test('reference-ion calibration recovers a known unequal-charge mass',()=>{const a=ion('133Xe',2),r=ion('133Cs'),m=P.mrtof([a,r],{...p,delayUs:120});const c=P.calibration(m.species[0].time/1000,m.species[1].time/1000,r,a.q,120,0,0,0);near(c.atomicMassU,a.M,1e-10);assert.throws(()=>P.calibration(1,2,r,1,2));});
test('ideal Penning frequencies obey both invariants and reject confinement',()=>{const a=ion('133Cs'),f=P.penning(a,7,10,.01);near(f.np+f.nm,f.nc,1e-7);near((f.np*f.np+f.nm*f.nm+f.nz*f.nz)/(f.nc*f.nc),1,1e-12);assert.equal(P.penning(a,7,-1,.01).stable,false);assert.equal(P.penning(a,7,0,.01).marginal,true);assert.equal(P.penning(a,.1,100,.001).stable,false);assert.throws(()=>P.frequency(a,0));});
// Independent complex two-level propagator: pulse -> free evolution -> pulse.
const cmul=(a,b)=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]],add=(a,b)=>[a[0]+b[0],a[1]+b[1]];
function propagate(amp,delta,coupling,time){const o=Math.hypot(delta,coupling),c=Math.cos(o*time/2),s=Math.sin(o*time/2);const U=[[[c,-s*delta/o],[0,-s*coupling/o]],[[0,-s*coupling/o],[c,s*delta/o]]];return U.map(row=>add(cmul(row[0],amp[0]),cmul(row[1],amp[1])));}
test('rectangular and Ramsey profiles match independent complex propagation',()=>{for(const T of [.01,.2,1])for(const d of [-50,-3.3,0,2,71])for(const scheme of ['rect','ramsey']){let amp=[[1,0],[0,0]],delta=2*Math.PI*d;if(scheme==='rect')amp=propagate(amp,delta,Math.PI/T,T);else{const tau=.1*T; amp=propagate(amp,delta,Math.PI/(2*tau),tau);amp=[cmul(amp[0],[Math.cos(delta*.8*T/2),-Math.sin(delta*.8*T/2)]),cmul(amp[1],[Math.cos(delta*.8*T/2),Math.sin(delta*.8*T/2)])];amp=propagate(amp,delta,Math.PI/(2*tau),tau);}near(P.conversion(d,T,scheme),amp[1][0]**2+amp[1][1]**2,2e-12);assert.ok(P.conversion(d,T,scheme)>=0&&P.conversion(d,T,scheme)<=1+1e-12);}});
test('mixture averages flight times, coincident species and zero populations',()=>{const a=ion('133Cs',1,70),b=ion('133Xe',1,30),par={B:7,T:.2,scheme:'rect'},f=P.frequency(a,7);near(P.mixture([a,b],f,par),.7*P.tofMean(1)+.3*P.tofMean(P.conversion(f-P.frequency(b,7),.2)));near(P.mixture([a,{...a,w:30}],f,par),P.tofMean(1));near(P.mixture([a,{...b,w:0}],f,par),P.tofMean(1));assert.throws(()=>P.mixture([{...a,w:0}],f,par));});
test('seeded acquisition is reproducible and fits exact single species',()=>{const a=ion('133Cs'),par={B:7,T:.2,scheme:'rect'},f=P.frequency(a,7);assert.deepEqual(P.acquire([a],par,f-20,f+20),P.acquire([a],par,f-20,f+20));const scan=Array.from({length:41},(_,j)=>{const x=f-10+j/2;return {f:x,mean:P.mixture([a],x,par),se:1,n:20}}),fit=P.fitSingle(scan,par,f);assert.equal(fit.status,'ok');near(fit.center,f,1e-4);assert.ok(fit.interval[0]<f&&fit.interval[1]>f);assert.equal(P.fitSingle(scan.slice(0,3),par,f).status,'insufficient data');assert.equal(P.fitSingle(scan.map(r=>({...r,f})),par,f).status,'insufficient data');});
test('seeded repetitions assess intervals; mixtures expose condition-dependent bias',()=>{const a=ion('133Cs'),b=ion('133Xe'),par={B:7,T:.2,scheme:'rect'},f=P.frequency(a,7);let covered=0,bias=0;for(let seed=1;seed<=40;seed++){const fit=P.fitSingle(P.acquire([a],par,f-12,f+12,41,300,seed).scan,par,f);assert.equal(fit.status,'ok');bias+=fit.bias;if(fit.interval[0]<=f&&fit.interval[1]>=f)covered++;}assert.ok(Math.abs(bias/40)<.1);assert.ok(covered>=18&&covered<=38,`coverage ${covered}/40`);const mix=P.fitSingle(P.acquire([a,b],par,f-20,f+20,31,500,20261007).scan,par,f);assert.ok(Math.abs(mix.bias)>.3);assert.ok(mix.reducedChi2>1.5);});
test('PI-ICR wrapping, radius zero, event width and centroid floor',()=>{const a=P.phaseResolution(8e5,.05,11,.6,100,.002),b=P.phaseResolution(8e5,.05,11,.6,400,.002);near(a.eventSigma,b.eventSigma);assert.ok(b.centroidSigma<a.centroidSigma&&b.centroidSigma>.002);near(a.frequencySigma,a.centroidSigma/(2*Math.PI*.05));assert.equal(P.phaseResolution(8e5,.05,0,.6,100).defined,false);assert.equal(P.phaseResolution(8e5,.05,11,.6,100,-1).defined,false);near(P.wrapPhase(-Math.PI),Math.PI);near(P.wrapPhase(2*Math.PI),0);near(P.wrapPhase(2*Math.PI*1000.25),Math.PI/2,1e-10);});
test('RFQ stability matches independent Fourier eigenvalue reference',()=>{const r=require('./mathieu-reference.json');for(const x of r.rows){near(P.mathieuA0(x.q),x.a0,r.tolerance);near(P.mathieuB1(x.q),x.b1,r.tolerance);}assert.equal(P.mathieuStable(0,.5),true);assert.equal(P.mathieuStable(0,1),false);assert.equal(P.mathieuStable(.3,.705996),false);const a=ion('133Cs'),x=P.mathieuParameters(a,10,100,4.5,1),y=P.mathieuParameters(a,20,200,9,2);near(y.a,x.a/8);near(y.q,x.q/8);});
test('RFQ cutoff intersections bracket the independently tested stability region',()=>{const c=P.rfqCutoffs(10,600,10,1);assert.equal(c.status,'window');near(c.aHigh,P.mathieuB1(c.qHigh),1e-10);near(-c.aLow,P.mathieuA0(c.qLow),1e-10);for(const mass of [c.lowMassU*.99,c.lowMassU*1.01,c.highMassU*.99,c.highMassU*1.01]){const q=c.qHigh*c.lowMassU/mass;assert.equal(P.mathieuStable(c.slope*q,q),mass>c.lowMassU&&mass<c.highMassU);}const rf=P.rfqCutoffs(0,600,10,1);near(rf.qHigh,.9080463337,1e-9);assert.equal(rf.highMassU,Infinity);assert.equal(P.rfqCutoffs(1,0,10,1).status,'rf-off');assert.equal(P.rfqCutoffs(101,600,10,1).status,'no-window');const scale=P.rfqCutoffs(10,600,20,2);near(scale.lowMassU,c.lowMassU/16,1e-10);near(P.rfqCutoffs(-10,600,10,1).lowMassU,c.lowMassU);});

test('PI time target honors widths, wrapping, coincidences and search domain',()=>{near(P.shortestPhaseTime([1000,1001],.02,3),9.55,1e-12);assert.equal(P.shortestPhaseTime([1,1],.02,1),null);assert.equal(P.shortestPhaseTime([1,2],1,4),null);const t=P.shortestPhaseTime([1000,1001,1009],.05,10);assert.ok(t>0);for(const delta of [1,8,9]){const phase=P.wrapPhase(2*Math.PI*delta*t/1000);assert.ok(Math.min(phase,2*Math.PI-phase)>=.5-1e-12);}assert.ok(P.shortestPhaseTime([1000,1001],.02,6)>P.shortestPhaseTime([1000,1001],.02,.5));});
test('mass-energy angle agrees with inverse-mass frequency and common origin cancels',()=>{const ref=ion('133Xe'),r=P.phaseEnergyStep(ref,7,.05);const heavy={...ref,ionMassU:ref.ionMassU+1/P.C.uKeV};near(r.deltaHz,P.frequency(heavy,7)-P.frequency(ref,7),1e-9);assert.ok(r.angleDeg<0);near(P.phaseEnergyStep(ref,7,.1).angleDeg,2*r.angleDeg);near(P.phaseEnergyStep({...ref,q:2},7,.05).angleDeg,2*r.angleDeg);const f=[1000,1001.5],t=.5/(f[1]-f[0]);for(const origin of [0,Math.PI/2,Math.PI,2*Math.PI]){const a=P.wrapPhase(2*Math.PI*f[0]*t+origin),b=P.wrapPhase(2*Math.PI*f[1]*t+origin);near(Math.abs(P.wrapPhase(b-a+Math.PI)-Math.PI),Math.PI,1e-10);}assert.equal(P.phaseEnergyStep(ref,7,0).angleDeg,0);});
